<?php

namespace backend\modules\Accounts\models;

use common\behance\lib\BehanceAccount;
use common\models\Debug;
use Yii;

/**
 * This is the model class for table "accounts".
 *
 * @property int $id
 * @property string $url
 * @property string $title
 */
class Accounts extends \common\models\Accounts
{
	public function beforeSave( $insert ) {
		$post = $_POST['Accounts'];
		if($post['url']){
			$acc = new BehanceAccount($post['url']);
  	        $this->username = $acc->username;
			$this->behance_id = $acc->behanceId;
			$this->image = $acc->image;
			$this->display_name = $acc->displayName;
			$this->url = $acc->url;
			$this->save();
		}
		return parent::beforeSave( $insert ); // TODO: Change the autogenerated stub
	}

}
